version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000 --settings=config.settings.local_docker
    volumes:
      - .:/code
      - /code/bbmajors_compute/compute_engine/engine/
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    image: postgres:11